-- Silver passthrough: beneficial_ownership
CREATE OR REFRESH MATERIALIZED VIEW elexon_app_for_settlement_acc_catalog.investec_fraud_aml_silver.beneficial_ownership AS
SELECT * FROM elexon_app_for_settlement_acc_catalog.investec_fraud_aml_bronze.beneficial_ownership;
